### register

POST http://127.0.0.1:5000/register
Content-Type: application/json

{
    "username": "a",
    "password": "a"
}

### login

POST http://127.0.0.1:5000/login
Content-Type: application/json

{
    "username": "a",
    "password": "a"
}

### logout
POST http://127.0.0.1:5000/logout

### protected route
POST http://127.0.0.1:5000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1IiwiaWF0IjoxNjg0ODU4Mzk3LCJleHAiOjE2ODQ4NTkyOTd9.S06P6-ceI7rano8jKFOVcK0ScT65AA5KFT1DIWI4VTY

### refresh token
POST http://127.0.0.1:5000/refresh_token
Cookie: refreshtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1IiwiaWF0IjoxNjg0ODU4Mzc2LCJleHAiOjE2ODQ5NDQ3NzZ9.4oK0GZx7_J4Q2rHCL37tVM1c5hn3xaNgjSdpVHtEWdY; Path=/refresh_token; HttpOnly

