### register
POST http://127.0.0.1:5000/accounts/register
Content-Type: application/json

{
    "username": "a",
    "password": "a"
}

### login
POST http://127.0.0.1:5000/accounts/login
Content-Type: application/json

{
    "username": "a",
    "password": "a"
}

### logout
POST http://127.0.0.1:5000/accounts/logout

### protected route
POST http://127.0.0.1:5000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1IiwiaWF0IjoxNjg2NjcwODY1LCJleHAiOjE2ODY2NzExNjV9.MKwqLoFlaHoetOIXJvtl6dqRcrBSF4w86IFWDmd4eJo

### refresh token
POST http://127.0.0.1:5000/accounts/refresh_token
Cookie: refreshtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1IiwiaWF0IjoxNjg2OTI0NTgxLCJleHAiOjE2ODcwMTA5ODF9.LQIU7Tm1xLzrlxuaSTPO1CUjhwZaIOFVkcjfsBe0i78; Path=/accounts/refresh_token; HttpOnly


########################################################
## CALC ROUTES
########################################################
POST http://127.0.0.1:5000/calc/load
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OCIsImlhdCI6MTY4NzgwMzE5OSwiZXhwIjoxNjg3ODA0OTk5fQ.DBk3XAf5HpIAZYNT_pRb6Xk-P_YltyVmR3PcdkStAfo
