### register
POST http://127.0.0.1:5000/accounts/register
Content-Type: application/json

{
    "username": "a",
    "password": "a"
}

### login
POST http://127.0.0.1:5000/accounts/login
Content-Type: application/json

{
    "username": "a",
    "password": "a"
}

### logout
POST http://127.0.0.1:5000/accounts/logout

### protected route
POST http://127.0.0.1:5000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1IiwiaWF0IjoxNjg2NjcwODY1LCJleHAiOjE2ODY2NzExNjV9.MKwqLoFlaHoetOIXJvtl6dqRcrBSF4w86IFWDmd4eJo

### refresh token
POST http://127.0.0.1:5000/accounts/refresh_token
Cookie: refreshtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1IiwiaWF0IjoxNjg2NzQ4ODE5LCJleHAiOjE2ODY4MzUyMTl9.lghVy9o2Dp827keqnan-fp4FaRu4fM1PAdnSIGjSrsY; Path=/accounts/refresh_token; HttpOnly
